export  const ActionType = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SELECTED_CATEGORE_PRODUCT: "SELECTED_CATEGORE_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SEARCH_VALUE:"SEARCH_VALUE",
  SET_IMAG:"SET_IMAG",
  COUNT_VALUE:"COUNT_VALUE",
  LANGUE_VALUE:"LANGUE_VALUE",
  CARSELIMENT_VALUE:"CARSELIMENT_VALUE",
  El_VALUE:"El_VALUE",
  SET_PRODFEAT:"SET_PRODFEAT",
  SET_SCROL:"SET_SCROL",
};

